console.log("Hello Guys")
console.log(10-5)
console.log(4.5-0.9)
console.log(4*2)
console.log(9/3)
console.log(9%3)
console.log("Dale" + " Tigre")
console.log("DaleTigre"[1])
console.log("DaleTigre".length)
console.log(("Dale" + "Tigre")[6])
console.log("um iphone custa " + 6000 + " reais no BR")